# Plotando

## plot

exemplo

```{r}
df <- readRDS("df.rds")
head(df)
```

plot basico

```{r}
args(plot)
```

então

```{r}
plot(x = df$tempo, y = df$MediaHoraria)
```


feio, ne?

```{r}
plot(x = df$tempo[1:100], y = df$MediaHoraria[1:100], 
     pch = 16, type = "b", col = "blue",
     xlab = "horas", ylab = "NO2[ppb]",
     main = "Plot menos feio")

```


Vamos a colocar **DOIS** plots


```{r}
plot(x = df$tempo[1:100], y = df$MediaHoraria[101:200], 
     pch = 16, type = "b", col = "blue",
     xlab = "horas", ylab = "NO2[ppb]",
     main = "Plot estranho")
lines(x = df$tempo[1:100], y = df$MediaHoraria[1:100], 
     pch = 15, type = "b", col = "red")

```

Se tu é fan de BASE PLOT, tudo bem :)


## ggplot

Tem um monte de recursos para ggplot na web

```{r}
library(ggplot2)
ggplot(df)
```



```{r}
ggplot(df, aes(x = tempo, y = MediaHoraria))
```



```{r}
ggplot(df, aes(x = tempo, y = MediaHoraria)) + 
  geom_line()
```

opa


```{r}
ggplot(df, aes(x = tempo, y = MediaHoraria, colour = mes)) + 
  geom_line() 
```


deixando so 2014 
```{r}
df <- df[df$ano == 2014,]
```


```{r}
ggplot(df, aes(x = tempo, y = MediaHoraria, colour = mes)) + 
  geom_line() +
  theme_bw()
```


```{r}

ggplot(df, aes(x = tempo, y = MediaHoraria, colour = MediaHoraria)) + 
  geom_line() 
```



```{r}
ggplot(df, aes(x = tempo, y = MediaHoraria, colour = MediaHoraria)) + 
  geom_line() +
  facet_wrap(~mes)
```


```{r}
ggplot(df, aes(x = tempo, y = MediaHoraria, colour = MediaHoraria)) + 
  geom_line() +
  facet_wrap(~mes, scales = "free")
```

Y para terminar, meu theme favorito

```{r eval = FALSE}
devtools::install_github("atmoschem/veinreport")
```

e logo
```{r}
library(veinreport)
library(cptcity)
```




```{r}
ggplot(df, aes(x = tempo, y = MediaHoraria, colour = MediaHoraria)) + 
  geom_line()+
  theme_black() +
  scale_color_gradientn(colours = cpt())
```

Pode revertir a escala de cores


```{r}
ggplot(df, aes(x = tempo, y = MediaHoraria, colour = MediaHoraria)) + 
  geom_line()+
  theme_black() +
  scale_color_gradientn(colours = rev(cpt())) + 
  facet_wrap(~mes, scales = "free")
```


não gostou, tenta com a sorte


```{r}
ggplot(df, aes(x = tempo, y = MediaHoraria, colour = MediaHoraria)) + 
  geom_line()+
  theme_black() +
    facet_wrap(~mes, scales = "free") +
  scale_color_gradientn(colours = lucky())
```


```{r}
ggplot(df, aes(x = tempo, y = MediaHoraria, colour = MediaHoraria)) + 
  geom_line()+
  theme_black() +
    facet_wrap(~mes, scales = "free") +
  scale_color_gradientn(colours = lucky())
```


```{r}
ggplot(df, aes(x = tempo, y = MediaHoraria, colour = MediaHoraria)) + 
  geom_line()+
  theme_black() +
  scale_color_gradientn(colours = lucky())
```

